version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "CI"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 5
    reviewers:
      - "DiTo97"
